### ISSUE TITLE
eval only expects a javascript object from server

### ISSUE THREAD

**Issue by YoEight** [selectel/mongoDB-haskell#1]
Hi,

eval function in Database.MongoDB.Query module only expects a javascript object from server.

this will failed

``` haskell

eval (Javascript ([] :: [Field]) "return 5;")

```

You've to trick it like this

``` haskell

eval (Javascript ([] :: [Field]) "return {foo: 5};")

```

**Comment by knsd** [comment]
Thanks for the issue!
I will change eval function's signature to `eval :: (MonadIO m, Val v) => Javascript -> Action m v` in next release.
