### ISSUE TITLE
line 70 doesn't compile in Pipeline if base is not 4.6.0

### ISSUE THREAD

**Issue by VictorDenisov** [selectel/mongoDB-haskell#19]
The problem is that if base is not 4.6.0 then

mkWeakMVar is defined as

mkWeakMVar :: MVar a -> IO () -> IO ()  
mkWeakMVar = addMVarFinalizer 

and
line 70:
_ <- mkWeakMVar

is incorrect then.

**Comment by knsd** [comment]
Hello, Victor. Can you please provide full trace?

**Comment by VictorDenisov** [comment]
victor@victor-alto:~/projects/haskell/moe$ cabal install mongoDB
Resolving dependencies...
Configuring mongoDB-1.4.2...
Building mongoDB-1.4.2...
Preprocessing library mongoDB-1.4.2...

System/IO/Pipeline.hs:5:14:
    Warning: -XRecursiveDo is deprecated: use -XDoRec or pragma {-# LANGUAGE DoRec #-} instead
[1 of 8] Compiling System.IO.Pool   ( System/IO/Pool.hs, dist/build/System/IO/Pool.o )
[2 of 8] Compiling System.IO.Pipeline ( System/IO/Pipeline.hs, dist/build/System/IO/Pipeline.o )

System/IO/Pipeline.hs:70:17: parse error on input `let'
Failed to install mongoDB-1.4.2
cabal: Error: some packages failed to install:
mongoDB-1.4.2 failed during the building phase. The exception was:
ExitFailure 1

**Comment by VictorDenisov** [comment]
My version of base package is 4.5.0

**Comment by knsd** [comment]
Thanks, Victor. Working version already at Hackage.

**Comment by VictorDenisov** [comment]
Thanks for the quick response.
