### ISSUE TITLE
Text package conflict

### ISSUE THREAD

**Issue by machunter** [selectel/mongoDB-haskell#23]
I am (very) new to Haskell and running into a problem using the mongodb driver (too ambitious for a start project?).  

I was getting the following error and couldn't make sense of it.

```
    Couldn't match type `Data.Text.Text'
                  with `text-0.11.3.1:Data.Text.Internal.Text'
```

After scouring the web the only related information I found was that this is pointing out to a "conflict" between the text libraries on my machine.
Indeed when I listed the packages I found that there was 2 versions of text:

```
ghc-pkg list | grep text
    text-0.11.3.1
    text-1.1.0.1
```

So when I hid the later version from my install with

```
ghc-pkg hide text-1.1.0.1
```

The error went away.
I am not sure whether what I am doing is ok and wondering whether the driver would support the later version of text?
Thanks.

**Comment by knsd** [comment]
Hi, @machunter, driver currently supports any version of `text`. It was actually a local problem, maybe it's better to use something like [cabal sandboxes](http://www.haskell.org/cabal/users-guide/installing-packages.html#developing-with-sandboxes) to avoid it.
