### ISSUE TITLE
release latest version as 2.0

### ISSUE THREAD

**Issue by gregwebs** [selectel/mongoDB-haskell#26]
Can we get the new version with the new monad stack released? Otherwise this will hold up the persistent 2.0 release.

Please pull in #25 first.

Can we bump the driver version to 2.0 for this release?
This makes it simple if anyone wants to delay the transition to 2.0.
As mentioned, I ported #25 to the 1.4.x released code and it works fine. So that can then be released as 1.5.

**Comment by gregwebs** [comment]
Do you want to add me as a maintainer on hackage and github so I can do the release?

**Comment by knsd** [comment]
Hello, Greg!

I've added your account on hackage and into the new mongodb-haskell organization on github.

**Comment by gregwebs** [comment]
thanks!
