### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by superbobry** [selectel/mongoDB-haskell#8]
Please make the code comply with [haskell-style-guide](https://github.com/tibbe/haskell-style-guide).

**Comment by btv** [comment]
I would like to help with this, can someone recommend a file to start with?

**Comment by superbobry** [comment]
@btv, we're currently thinking on doing a from scratch rewrite of this driver, so the issue isn't relevant.

**Comment by gregwebs** [comment]
should this issue be closed?

**Comment by knsd** [comment]
Yes, I agree.
